"""Build a viewable copy of the methodology figures page.

    python new-revisited-writing/build_standalone.py

`figures-methodology.html` is the artifact SOURCE. The artifact host wraps it
in a document and injects a mermaid runtime that turns each
`<pre class="mermaid">` block into a diagram. Opened as a local file it has
neither, so figures 0 and 1 show as walls of mermaid source -- the page looks
broken. This script writes `figures-methodology.standalone.html`: the same
content, wrapped in a real document, with mermaid loaded from a CDN and
initialised exactly as the host initialises it.

The source file is never modified. Rebuild after editing it.

WHY NOT INLINE PRE-RENDERED SVG. That was the first attempt and it was wrong.
mermaid sizes every node from the text metrics of the font in use at render
time; render headlessly without the page's webfont and every label is measured
in a fallback face, so the boxes come out too narrow and the displayed text is
clipped ("Differentiable rasterisatio"). Rendering in the browser that
displays the page makes the measuring font and the display font the same one
by construction. It costs a network fetch on first open, which the page
already pays for its typefaces.

OFFLINE. Without network, the diagrams stay visible as mermaid source and the
banner says so -- degraded, not blank. Figure 2 is hand-written SVG in the
source and always draws.
"""

from __future__ import annotations

import re
from pathlib import Path

HERE: Path = Path(__file__).resolve().parent
SOURCE: Path = HERE / "figures-methodology.html"
TARGET: Path = HERE / "figures-methodology.standalone.html"

LIVE_URL: str = "https://claude.ai/artifact/BqdkonmDqJsFYcVTcWJfKG"

# Pinned to the version the artifact host serves, so the offline copy and the
# live page lay out identically. cdnjs is also the CDN the host's own content
# policy allows, which keeps this file publishable if it is ever wanted.
MERMAID_SRC: str = (
    "https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.16.1/mermaid.min.js"
)

# The host's own mermaid settings, transcribed from its injected runtime.
# securityLevel 'strict' is the one that matters: it strips HTML from node
# labels, which is why the diagram sources use mermaid markdown strings.
INIT: str = """
  mermaid.initialize({
    startOnLoad: false,
    securityLevel: 'strict',
    theme: 'base',
    flowchart: { useMaxWidth: false },
    themeVariables: {
      background: bg, mainBkg: pal.surface, primaryColor: pal.surface,
      primaryTextColor: pal.text, lineColor: pal.line,
      primaryBorderColor: pal.border, nodeBorder: pal.border,
      clusterBorder: pal.border, edgeLabelBackground: bg,
      clusterBkg: 'rgba(127,127,127,0.07)', titleColor: pal.text,
      darkMode: dark, fontSize: '16px',
      fontFamily: getComputedStyle(document.body).fontFamily || 'sans-serif'
    },
    themeCSS: '.node rect, .node circle, .node polygon, .node path, ' +
              '.cluster rect { stroke-width: 2px; }'
  });
"""

HEAD: str = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  /* The artifact host supplies these; a standalone file has to. */
  :root {{ color-scheme: light dark; }}
  body {{ margin: 0; }}
  img {{ max-width: 100%; }}
  [hidden] {{ display: none !important; }}
  .offline-note {{
    max-width: 1060px; margin: 0 auto; padding: 14px 28px 0;
    font: 13px/1.55 "IBM Plex Mono", ui-monospace, monospace; color: #7C908F;
  }}
  .offline-note a {{ color: #C8462E; }}
  .mermaid-diagram svg {{
    display: block; margin: 0 auto; max-width: 100%; height: auto;
  }}
</style>
</head>
<body>
<div class="offline-note">
  Local copy, built from <code>figures-methodology.html</code> by
  <code>build_standalone.py</code>. The two pipeline diagrams are drawn in your
  browser from mermaid source, as they are on the live page at
  <a href="{LIVE_URL}">claude.ai</a>; with no network they stay visible as that
  source. Do not edit this file -- edit the source and rebuild.
</div>
"""

RUNTIME: str = f"""
<script src="{MERMAID_SRC}"></script>
<script>
(function () {{
  if (typeof mermaid === 'undefined') return;   /* offline: leave the source */
  var pres = Array.prototype.slice.call(
    document.querySelectorAll('pre.mermaid'));
  if (!pres.length) return;
  var mq = window.matchMedia
    ? window.matchMedia('(prefers-color-scheme: dark)') : null;
  var root = document.documentElement;
  var items = pres.map(function (pre) {{
    var mount = document.createElement('div');
    mount.className = 'mermaid-diagram';
    return {{ pre: pre, mount: mount, src: pre.textContent || '' }};
  }});
  var seq = 0, gen = 0, lastKey = '';

  function pageBg(fallback) {{
    var els = [document.body, document.documentElement];
    for (var i = 0; i < els.length; i++) {{
      var c = els[i] && getComputedStyle(els[i]).backgroundColor;
      if (c && c !== 'transparent' && c !== 'rgba(0, 0, 0, 0)') return c;
    }}
    return fallback;
  }}

  function render() {{
    var theme = root.getAttribute('data-theme');
    var dark = theme === 'dark' || (!!(mq && mq.matches) && theme !== 'light');
    var pal = dark
      ? {{ surface: '#132223', text: '#E4EDEC', line: '#6E8382',
          border: '#26393B', bg: '#0B1516' }}
      : {{ surface: '#FFFFFF', text: '#10201F', line: '#7C908F',
          border: '#94A9A8', bg: '#FFFFFF' }};
    var bg = pageBg(pal.bg);
    var key = (dark ? 'd' : 'l') + '|' + bg;
    if (key === lastKey) return;
    lastKey = key;
    var mine = ++gen;
{INIT}
    items.forEach(function (it) {{
      var id = 'fig-' + (seq++);
      mermaid.render(id, it.src).then(function (r) {{
        if (mine !== gen) return;
        it.mount.innerHTML = r.svg;
        if (!it.mount.parentNode) {{
          it.pre.parentNode.insertBefore(it.mount, it.pre);
        }}
        it.pre.style.display = 'none';
      }}, function () {{
        var scratch = document.getElementById(id);
        if (scratch) scratch.parentNode.removeChild(scratch);
        scratch = document.getElementById('d' + id);
        if (scratch) scratch.parentNode.removeChild(scratch);
        if (mine !== gen) return;
        if (it.mount.parentNode) it.mount.parentNode.removeChild(it.mount);
        it.pre.style.display = '';   /* failed: show the source, not a gap */
      }});
    }});
  }}

  /* Fonts change text metrics, so lay out once the webfonts have landed. */
  if (document.fonts && document.fonts.ready) {{
    document.fonts.ready.then(render);
  }} else {{
    render();
  }}
  if (mq && mq.addEventListener) mq.addEventListener('change', render);
}})();
</script>
</body>
</html>
"""

BLOCK: re.Pattern[str] = re.compile(r'<pre class="mermaid">\r?\n(.*?)</pre>', re.S)


def build() -> None:
    source: str = SOURCE.read_text(encoding="utf-8")
    blocks: list[str] = BLOCK.findall(source)
    if not blocks:
        raise SystemExit(
            f"{SOURCE.name} has no mermaid blocks -- did its format change?"
        )
    TARGET.write_text(HEAD + source + RUNTIME, encoding="utf-8")
    size_kb: float = TARGET.stat().st_size / 1024
    print(f"{TARGET.name}: {len(blocks)} diagram(s), {size_kb:.0f} KB")


if __name__ == "__main__":
    build()
